/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CourseRouteImport } from './routes/course'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as CourseNewRouteImport } from './routes/course.new'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course.$courseId.index'
import { Route as GamesessionGameSessionIdGamesessionRouteImport } from './routes/gamesession_/$gameSessionId/gamesession'
import { Route as GamesessionGameSessionIdSessionlayoutRouteImport } from './routes/gamesession_/$gameSessionId/_sessionlayout'
import { Route as CourseCourseIdNewgameRouteImport } from './routes/course.$courseId.newgame'
import { Route as CourseCourseIdEditRouteImport } from './routes/course.$courseId.edit'
import { Route as GamesessionGameSessionIdSessionlayoutMapRouteImport } from './routes/gamesession_/$gameSessionId/_sessionlayout.map'

const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseNewRoute = CourseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CourseRoute,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/$courseId/',
  path: '/$courseId/',
  getParentRoute: () => CourseRoute,
} as any)
const GamesessionGameSessionIdGamesessionRoute =
  GamesessionGameSessionIdGamesessionRouteImport.update({
    id: '/gamesession_/$gameSessionId/gamesession',
    path: '/gamesession/$gameSessionId/gamesession',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesessionGameSessionIdSessionlayoutRoute =
  GamesessionGameSessionIdSessionlayoutRouteImport.update({
    id: '/gamesession_/$gameSessionId/_sessionlayout',
    path: '/gamesession/$gameSessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseCourseIdNewgameRoute = CourseCourseIdNewgameRouteImport.update({
  id: '/$courseId/newgame',
  path: '/$courseId/newgame',
  getParentRoute: () => CourseRoute,
} as any)
const CourseCourseIdEditRoute = CourseCourseIdEditRouteImport.update({
  id: '/$courseId/edit',
  path: '/$courseId/edit',
  getParentRoute: () => CourseRoute,
} as any)
const GamesessionGameSessionIdSessionlayoutMapRoute =
  GamesessionGameSessionIdSessionlayoutMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => GamesessionGameSessionIdSessionlayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course': typeof CourseRouteWithChildren
  '/course/new': typeof CourseNewRoute
  '/auth/': typeof AuthIndexRoute
  '/course/': typeof CourseIndexRoute
  '/course/$courseId/edit': typeof CourseCourseIdEditRoute
  '/course/$courseId/newgame': typeof CourseCourseIdNewgameRoute
  '/gamesession/$gameSessionId': typeof GamesessionGameSessionIdSessionlayoutRouteWithChildren
  '/gamesession/$gameSessionId/gamesession': typeof GamesessionGameSessionIdGamesessionRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/gamesession/$gameSessionId/map': typeof GamesessionGameSessionIdSessionlayoutMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course/new': typeof CourseNewRoute
  '/auth': typeof AuthIndexRoute
  '/course': typeof CourseIndexRoute
  '/course/$courseId/edit': typeof CourseCourseIdEditRoute
  '/course/$courseId/newgame': typeof CourseCourseIdNewgameRoute
  '/gamesession/$gameSessionId': typeof GamesessionGameSessionIdSessionlayoutRouteWithChildren
  '/gamesession/$gameSessionId/gamesession': typeof GamesessionGameSessionIdGamesessionRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/gamesession/$gameSessionId/map': typeof GamesessionGameSessionIdSessionlayoutMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course': typeof CourseRouteWithChildren
  '/course/new': typeof CourseNewRoute
  '/auth/': typeof AuthIndexRoute
  '/course/': typeof CourseIndexRoute
  '/course/$courseId/edit': typeof CourseCourseIdEditRoute
  '/course/$courseId/newgame': typeof CourseCourseIdNewgameRoute
  '/gamesession_/$gameSessionId/_sessionlayout': typeof GamesessionGameSessionIdSessionlayoutRouteWithChildren
  '/gamesession_/$gameSessionId/gamesession': typeof GamesessionGameSessionIdGamesessionRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/gamesession_/$gameSessionId/_sessionlayout/map': typeof GamesessionGameSessionIdSessionlayoutMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course'
    | '/course/new'
    | '/auth/'
    | '/course/'
    | '/course/$courseId/edit'
    | '/course/$courseId/newgame'
    | '/gamesession/$gameSessionId'
    | '/gamesession/$gameSessionId/gamesession'
    | '/course/$courseId/'
    | '/gamesession/$gameSessionId/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/course/new'
    | '/auth'
    | '/course'
    | '/course/$courseId/edit'
    | '/course/$courseId/newgame'
    | '/gamesession/$gameSessionId'
    | '/gamesession/$gameSessionId/gamesession'
    | '/course/$courseId'
    | '/gamesession/$gameSessionId/map'
  id:
    | '__root__'
    | '/'
    | '/course'
    | '/course/new'
    | '/auth/'
    | '/course/'
    | '/course/$courseId/edit'
    | '/course/$courseId/newgame'
    | '/gamesession_/$gameSessionId/_sessionlayout'
    | '/gamesession_/$gameSessionId/gamesession'
    | '/course/$courseId/'
    | '/gamesession_/$gameSessionId/_sessionlayout/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseRoute: typeof CourseRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  GamesessionGameSessionIdSessionlayoutRoute: typeof GamesessionGameSessionIdSessionlayoutRouteWithChildren
  GamesessionGameSessionIdGamesessionRoute: typeof GamesessionGameSessionIdGamesessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof CourseRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/new': {
      id: '/course/new'
      path: '/new'
      fullPath: '/course/new'
      preLoaderRoute: typeof CourseNewRouteImport
      parentRoute: typeof CourseRoute
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/$courseId'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof CourseRoute
    }
    '/gamesession_/$gameSessionId/gamesession': {
      id: '/gamesession_/$gameSessionId/gamesession'
      path: '/gamesession/$gameSessionId/gamesession'
      fullPath: '/gamesession/$gameSessionId/gamesession'
      preLoaderRoute: typeof GamesessionGameSessionIdGamesessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamesession_/$gameSessionId/_sessionlayout': {
      id: '/gamesession_/$gameSessionId/_sessionlayout'
      path: '/gamesession/$gameSessionId'
      fullPath: '/gamesession/$gameSessionId'
      preLoaderRoute: typeof GamesessionGameSessionIdSessionlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/newgame': {
      id: '/course/$courseId/newgame'
      path: '/$courseId/newgame'
      fullPath: '/course/$courseId/newgame'
      preLoaderRoute: typeof CourseCourseIdNewgameRouteImport
      parentRoute: typeof CourseRoute
    }
    '/course/$courseId/edit': {
      id: '/course/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/course/$courseId/edit'
      preLoaderRoute: typeof CourseCourseIdEditRouteImport
      parentRoute: typeof CourseRoute
    }
    '/gamesession_/$gameSessionId/_sessionlayout/map': {
      id: '/gamesession_/$gameSessionId/_sessionlayout/map'
      path: '/map'
      fullPath: '/gamesession/$gameSessionId/map'
      preLoaderRoute: typeof GamesessionGameSessionIdSessionlayoutMapRouteImport
      parentRoute: typeof GamesessionGameSessionIdSessionlayoutRoute
    }
  }
}

interface CourseRouteChildren {
  CourseNewRoute: typeof CourseNewRoute
  CourseIndexRoute: typeof CourseIndexRoute
  CourseCourseIdEditRoute: typeof CourseCourseIdEditRoute
  CourseCourseIdNewgameRoute: typeof CourseCourseIdNewgameRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
}

const CourseRouteChildren: CourseRouteChildren = {
  CourseNewRoute: CourseNewRoute,
  CourseIndexRoute: CourseIndexRoute,
  CourseCourseIdEditRoute: CourseCourseIdEditRoute,
  CourseCourseIdNewgameRoute: CourseCourseIdNewgameRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
}

const CourseRouteWithChildren =
  CourseRoute._addFileChildren(CourseRouteChildren)

interface GamesessionGameSessionIdSessionlayoutRouteChildren {
  GamesessionGameSessionIdSessionlayoutMapRoute: typeof GamesessionGameSessionIdSessionlayoutMapRoute
}

const GamesessionGameSessionIdSessionlayoutRouteChildren: GamesessionGameSessionIdSessionlayoutRouteChildren =
  {
    GamesessionGameSessionIdSessionlayoutMapRoute:
      GamesessionGameSessionIdSessionlayoutMapRoute,
  }

const GamesessionGameSessionIdSessionlayoutRouteWithChildren =
  GamesessionGameSessionIdSessionlayoutRoute._addFileChildren(
    GamesessionGameSessionIdSessionlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseRoute: CourseRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  GamesessionGameSessionIdSessionlayoutRoute:
    GamesessionGameSessionIdSessionlayoutRouteWithChildren,
  GamesessionGameSessionIdGamesessionRoute:
    GamesessionGameSessionIdGamesessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
