from typing import Optional, List, TYPE_CHECKING, Dict, Any
from datetime import datetime, UTC, date
import uuid
from sqlmodel import Field, SQLModel, Relationship, JSON, Column, func, DateTime
from ..game_session.model import utc_now_naive

if TYPE_CHECKING:
    from ..user.model import User


class DeviceSessionBase(SQLModel):
    has_identified: bool = False
    device_id_code: int = 0


class DeviceSession(DeviceSessionBase, table=True):
    # ID is the session id and should be uuid4 given at creation
    # Flow is such as: 1. user commands "add_device" in the bot API
    # 2. bot waits for an ID string generated by device
    # 3. When ID is received, this db entry is created
    # 4. Watch is sending the ID to backend and when its matched, backend returns the actual ID and sets has_identified to true. The ID session key is used for all other identification
    # 5. inform tg app about watch being connected or remove this db entry if user exits the pairing
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), primary_key=True)
    user_id: Optional[int] = Field(default=None, foreign_key="user.id")
    user: Optional["User"] = Relationship(back_populates="device_sessions")

    created_at: Optional[datetime] = Field(
        default_factory=utc_now_naive, sa_type=DateTime(timezone=False)
    )
    # TODO: save some sort of device specific specific id?


class RegisterDeviceData(SQLModel):
    device_id: int


class ReadDeviceSession(SQLModel):
    key: str
    username: str


class FrontReadDeviceSession(SQLModel):
    created_at: datetime
