"""Add telegram fields to user model

Revision ID: 20d8cf216ad8
Revises: c3ff5776ae64
Create Date: 2026-05-10 11:51:20.657083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "20d8cf216ad8"
down_revision: Union[str, Sequence[str], None] = "c3ff5776ae64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("user") as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###

        batch_op.add_column(
            sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
        batch_op.add_column(
            sa.Column("photo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
        batch_op.add_column(sa.Column("auth_date", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("user") as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.drop_column("hash")
        batch_op.drop_column("auth_date")
        batch_op.drop_column("photo_url")
        batch_op.drop_column("last_name")
        # ### end Alembic commands ###
