"""Add is_guest to user

Revision ID: 5ac6cfbbeab1
Revises: 8763062862f7
Create Date: 2026-06-21 16:42:07.881408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "5ac6cfbbeab1"
down_revision: Union[str, Sequence[str], None] = "8763062862f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.alter_column("par", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_guest", sa.Boolean(), nullable=True))
    op.execute("UPDATE user SET is_guest = true WHERE is_guest IS NULL")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("is_guest", existing_type=sa.Boolean(), nullable=False)

        batch_op.add_column(
            sa.Column("managed_by_user_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "managed_by_user", "user", ["managed_by_user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("managed_by_user", type_="foreignkey")
        batch_op.drop_column("managed_by_user_id")
        batch_op.drop_column("is_guest")

    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.alter_column("par", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
