"""Added distance field to track

Revision ID: 8763062862f7
Revises: d35efed84222
Create Date: 2026-06-16 17:00:31.828265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "8763062862f7"
down_revision: Union[str, Sequence[str], None] = "d35efed84222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.add_column(sa.Column("distance", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_column("distance")

    # ### end Alembic commands ###
