"""unique constraint fix

Revision ID: c3ff5776ae64
Revises: 
Create Date: 2025-09-01 13:35:33.439202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ff5776ae64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'score_unique',  # The name of the NEW constraint
        'score', 
        ['user_id', 'track_number', 'game_session_id']
    )
    op.drop_constraint(
        'track_number',  # The name of the OLD constraint
        'score', 
        type_='unique'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
