"""Add created at timestamp to score

Revision ID: ce70a185a61f
Revises: da8632093140
Create Date: 2026-05-24 10:55:19.911323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "ce70a185a61f"
down_revision: Union[str, Sequence[str], None] = "da8632093140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
