"""Added tee and basket locations to tracks

Revision ID: d35efed84222
Revises: ce70a185a61f
Create Date: 2026-05-29 11:49:11.499385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "d35efed84222"
down_revision: Union[str, Sequence[str], None] = "ce70a185a61f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tee_lat", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tee_lng", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("basket_lat", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("basket_lng", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_column("basket_lng")
        batch_op.drop_column("basket_lat")
        batch_op.drop_column("tee_lng")
        batch_op.drop_column("tee_lat")

    # ### end Alembic commands ###
