"""add throws table

Revision ID: da8632093140
Revises: 20d8cf216ad8
Create Date: 2026-05-13 12:34:20.206462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "da8632093140"
down_revision: Union[str, Sequence[str], None] = "20d8cf216ad8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "throw",
        sa.Column("throw_number", sa.Integer(), nullable=False),
        sa.Column("is_penalty", sa.Boolean(), nullable=False),
        sa.Column("start_lat", sa.Float(), nullable=True),
        sa.Column("start_lng", sa.Float(), nullable=True),
        sa.Column("end_lat", sa.Float(), nullable=True),
        sa.Column("end_lng", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("score_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["score.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###

    bind = op.get_bind()

    # Get all existing scores
    query = sa.text("""
        SELECT s.id, s.score, t.par 
        FROM score s
        JOIN track t ON s.track_number = t.track_number AND s.course_id = t.course_id
    """)
    scores = bind.execute(query).fetchall()

    throws_to_insert = []
    for row in scores:
        score_id = row[0]
        relative_score = row[1]
        par = row[2]
        actual_strokes = relative_score + par

        for throw_num in range(1, actual_strokes + 1):
            throws_to_insert.append(
                {"score_id": score_id, "throw_number": throw_num, "is_penalty": False}
            )
        bind.execute(
            sa.text("UPDATE score SET score = :actual_strokes WHERE id = :score_id"),
            {"actual_strokes": actual_strokes, "score_id": score_id},
        )

    # Bulk insert the new throws
    if throws_to_insert:
        # Create a temporary SQLAlchemy table object for bulk insert
        meta = sa.MetaData()
        throw_table = sa.Table(
            "throw",
            meta,
            sa.Column("score_id", sa.Integer()),
            sa.Column("throw_number", sa.Integer()),
            sa.Column("is_penalty", sa.Boolean()),
        )
        op.bulk_insert(throw_table, throws_to_insert)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.drop_table("throw")
    # ### end Alembic commands ###
