name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        # This job MUST run on your self-hosted server
        runs-on: [self-hosted, linux, prod-deploy] # Use the labels you configured

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: get repository name
              run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
            - name: Execute Deployment Script
              # Here we pass the GitHub Secrets as environment variables to the script
              env:
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_USER: ${{ secrets.DB_USER }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  API_KEY: ${{ secrets.API_KEY }}
              run: |
                  chmod +x ./deploy.sh
                  ./deploy.sh
